"""Compose and deliver a morning digest as a GitHub issue (→ email).

Run by the daily Action after the data refresh (before the slow price step, so
it is timely and needs only the trades + AI files). It builds a short markdown
report with three sections:

  1. **Featured stocks technical read** — the mechanical buy/hold/sell tally for each
     tracked ticker (from `indicators.ai_score`), with price / 1d / RSI / trend.
  2. **Signals overnight** — mechanical signals that fired on the latest bar
     (from `ai-indicators.json` meta.new_signals) plus any ticker whose
     buy/sell/hold rating flipped versus yesterday's report.
  3. **New congressional disclosures** — trades newly filed in the last few days.

Delivery is twofold: (1) **direct email via SMTP** (primary — reliable
regardless of GitHub notification settings; enabled by SMTP_USER/SMTP_PASS
secrets, e.g. a Gmail address + App Password), and (2) a **dated GitHub issue**
(archive + flip-diff state; assigned to the repo owner). It closes the previous
day's issue to keep the list tidy and records the issue number + the current
ratings in `congress/report_state.json` for tomorrow's diff.

**Quiet days do not send.** The market closes at the weekend and on holidays,
so a Sunday email repeats Saturday's word for word. When the latest daily close
has not advanced AND no new filing has arrived since the last report, the run
skips every delivery — email, subscriber broadcast, traffic email and issue —
and writes no dated permalink. It still publishes the web edition, so /report
stays current, and it records nothing in the state, so a later cron re-asks the
question. See ``whats_new``.

Everything except the GitHub API and SMTP calls is pure stdlib (`smtplib` is
stdlib too); `build_report` is tested offline. Non-fatal by design — a failed
report must not fail the data refresh. Run as a module
(`python3 -m congress.daily_report`) so the package's `http.py` does not shadow
stdlib `http`.
"""

from __future__ import annotations

import json
import os
import smtplib
import ssl
import sys
import urllib.error
import urllib.request
from datetime import date, datetime, timedelta, timezone
from email.message import EmailMessage
from pathlib import Path

from . import analytics, buttondown, email_template, indicators, pipeline

API = "https://api.github.com"
TRADES_JSON = pipeline.REPO_ROOT / "docs" / "data" / "congress-trades.json"
AI_JSON = pipeline.REPO_ROOT / "docs" / "data" / "ai-indicators.json"
HOLDINGS_JSON = pipeline.REPO_ROOT / "docs" / "data" / "holdings.json"
# Slug→name for the member-page traffic breakdown (generated by landing_data).
MEMBER_INDEX_JSON = (pipeline.REPO_ROOT / "landing" / "src" / "data"
                     / "members" / "_index.json")
STATE_JSON = pipeline.REPO_ROOT / "congress" / "report_state.json"
DISCLOSURE_WINDOW_DAYS = 3
MAX_DISCLOSURES = 20
PARTY = {"D": "D", "R": "R", "I": "I"}
DISCLAIMER = (
    "Mechanical technical readings from past daily closes + official STOCK Act "
    "disclosures (30–45-day legal lag, bracketed amounts). **Not investment "
    "advice.**"
)


def _load(path: Path, default):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return default


def _trend(t: dict) -> str:
    if t.get("sma50") is None or t.get("sma200") is None:
        return "—"
    return "50d›200d" if t["sma50"] >= t["sma200"] else "50d‹200d"


def _pct(x) -> str:
    if x is None:
        return "—"
    return f"{'+' if x > 0 else ''}{x}%"


# Public site — the email links back into it so readers land on the ticker
# pages (and so Vercel analytics can attribute the email as a traffic source).
# Overridable via the SITE_URL var (handy for pointing a run at a preview
# deployment); the apex domain is the default and the normal case.
SITE_URL = (os.environ.get("SITE_URL", "").strip().rstrip("/")
            or "https://capitolledger.io")
# The tracker now lives on the site itself (apex domain live 2026-07-28).
TRACKER_URL = f"{SITE_URL}/tracker"
EMAIL_UTM = "utm_source=email&utm_medium=report&utm_campaign=morning"
# Web edition of this email, linked from it ("view in browser"). The email
# links the DATED permalink (see report_url()), so an old email keeps showing
# the report it delivered instead of whatever is current.
REPORT_URL = f"{SITE_URL}/report?{EMAIL_UTM}"
# The web version of the report, rendered by landing/src/pages/report.astro.
REPORT_JSON = (pipeline.REPO_ROOT / "landing" / "src" / "data" / "report.json")
# The dated archive: one JSON per day + an index, rendered as noindex'd
# /report/<date> permalinks and the /report/archive list.
REPORTS_DIR = (pipeline.REPO_ROOT / "landing" / "src" / "data" / "reports")


def report_url(today_iso: str) -> str:
    """The dated permalink for today's report (what the email links)."""
    return f"{SITE_URL}/report/{today_iso}?{EMAIL_UTM}"
# Symbols that have a /tickers/<slug> page, written by landing_data.
TICKER_INDEX_JSON = (pipeline.REPO_ROOT / "landing" / "src" / "data"
                     / "tickers" / "_index.json")


def ticker_links(ticker_pages: dict | None, site: str | None = None) -> dict:
    """{SYMBOL: absolute UTM-tagged page URL} for the tickers that have a page."""
    base = (site or SITE_URL).rstrip("/")
    return {
        t["ticker"]: f"{base}/tickers/{t['slug']}?{EMAIL_UTM}"
        for t in (ticker_pages or {}).get("tickers", [])
        if t.get("ticker") and t.get("slug")
    }


def holdings_gaps(holdings: dict) -> list[str]:
    """Featured-member annual reports we could NOT parse, as display lines.

    Only ``NEEDS_REVIEW`` reasons count — a funds-only portfolio or an
    unsupported chamber is correct data, not a gap. This is the owner's
    keep-an-eye line: a newly featured member whose annual report turns out
    to be a scanned PDF shows up in the next morning email instead of only
    in the Action log."""
    from . import holdings as holdings_mod
    from .landing_data import MEMBER_PAGE_NAMES

    recs = (holdings or {}).get("holdings", {})
    gaps = []
    for name in MEMBER_PAGE_NAMES:
        rec = recs.get(name)
        if rec is None:
            gaps.append(f"{name} — not fetched yet")
            continue
        reason = rec.get("reason")
        if reason in holdings_mod.NEEDS_REVIEW:
            gaps.append(
                f"{name} — {holdings_mod.REASON_TEXT.get(reason, reason)}")
    return gaps


def build_report(trades: list[dict], ai_tickers: dict, new_signals: list[dict],
                 prev_ratings: dict, today_iso: str,
                 ticker_urls: dict | None = None,
                 coverage_gaps: list[str] | None = None) -> dict:
    """Compose the trade/scorecard digest in markdown (GitHub issue) and HTML
    (email). Site traffic is delivered in its own email — see
    ``build_traffic_email``. Pure — no I/O. Returns
    ``{markdown, html, ratings, counts}`` where ``ratings`` is ticker→label for
    the next run's flip diff."""
    order = [s["ticker"] for s in indicators.AI_TICKERS if s["ticker"] in ai_tickers]
    order += sorted(tk for tk in ai_tickers if tk not in order)

    # --- Section 1: Featured-stock scorecard ---
    ratings: dict[str, str] = {}
    rows, sc_rows = [], []
    for tk in order:
        t = ai_tickers[tk]
        sc = indicators.ai_score(t)
        ratings[tk] = sc["label"]
        price, chg = t.get("price", "—"), _pct(t.get("chg_1d"))
        rsi = "—" if t.get("rsi14") is None else round(t["rsi14"])
        trend = _trend(t)
        rows.append(
            f"| {tk} | ${price} | {chg} | {rsi} | {trend} | **{sc['label']}** |")
        chg_val = t.get("chg_1d") or 0
        sc_rows.append({
            "ticker": tk, "price": price, "chg": chg,
            "chg_dir": 1 if chg_val > 0 else (-1 if chg_val < 0 else 0),
            "rsi": rsi, "trend": trend, "label": sc["label"],
            "url": (ticker_urls or {}).get(tk),
        })
    scorecard = (
        "## ⭐ Featured stocks — technical read\n\n"
        "| Ticker | Price | 1d | RSI | Trend | Read |\n"
        "|---|---|---|---|---|---|\n" + "\n".join(rows) +
        "\n\n_Read = a rule-based tally of the indicators (each votes "
        "buy/hold/sell), not a recommendation._"
    ) if rows else "## ⭐ Featured stocks — technical read\n\n_No indicator data._"

    # --- Section 2: signals + rating flips ---
    sig_lines = [
        f"- **{s['ticker']}** — {s.get('label', s.get('type', 'signal'))} "
        f"({s.get('asof', '')})"
        for s in (new_signals or [])
    ]
    sig_data = [
        {"ticker": s["ticker"],
         "label": s.get("label", s.get("type", "signal")),
         "type": s.get("type"), "asof": s.get("asof", "")}
        for s in (new_signals or [])
    ]
    flips, flip_data = [], []
    for tk, label in ratings.items():
        prev = prev_ratings.get(tk)
        if prev and prev != label:
            flips.append(f"- **{tk}** rating: {prev} → {label}")
            flip_data.append({"ticker": tk, "prev": prev, "label": label})
    signals_md = "## 🔔 Signals overnight\n\n"
    if sig_lines or flips:
        if sig_lines:
            signals_md += "**New signals:**\n" + "\n".join(sig_lines) + "\n\n"
        if flips:
            signals_md += "**Rating changes:**\n" + "\n".join(flips) + "\n"
    else:
        signals_md += "_No new signals or rating changes since yesterday._\n"

    # --- Section 3: new congressional disclosures ---
    cutoff = (date.fromisoformat(today_iso) -
              timedelta(days=DISCLOSURE_WINDOW_DAYS)).isoformat()
    window = [t for t in trades if (t.get("filing_date") or "") >= cutoff]
    window.sort(key=lambda t: (t.get("filing_date", ""), t.get("tx_date", "")),
                reverse=True)
    # The EMAIL is a headline surface: stock/option rows only (owner's
    # call — one senator's muni-bond ladder was drowning the signal).
    # Bond/muni filings collapse to a count there, linking the /report
    # page — which shows the whole undivided picture.
    from .landing_data import is_bond
    recent = [t for t in window if not is_bond(t)]
    bond_count = len(window) - len(recent)
    disc_lines, disc_data = [], []
    for t in recent[:MAX_DISCLOSURES]:
        party = PARTY.get(t.get("party"))
        who = t.get("member", "?") + (f" ({party})" if party else "")
        name = t.get("ticker") or t.get("asset", "?")
        disc_lines.append(
            f"- {t.get('filing_date', '?')} · {who} · "
            f"**{name}** {t.get('type', '?')} · {t.get('amount_label', '—')}")
        disc_data.append({
            "filing_date": t.get("filing_date", "?"), "who": who, "name": name,
            "type": t.get("type", "?"), "amount": t.get("amount_label", "—"),
        })
    disclosures_md = "## 🏛 New disclosures " \
        f"(filed since {cutoff})\n\n"
    if disc_lines:
        disclosures_md += "\n".join(disc_lines) + "\n"
        if len(recent) > MAX_DISCLOSURES:
            disclosures_md += f"\n_…and {len(recent) - MAX_DISCLOSURES} more._\n"
    else:
        disclosures_md += "_No new stock/option disclosures in this window._\n"
    if bond_count:
        disclosures_md += (
            f"\n_…plus {bond_count} bond & muni filing"
            f"{'s' if bond_count != 1 else ''} — "
            f"[see the full report]({report_url(today_iso)})._\n")

    # --- Holdings coverage (owner's ops note; only rendered when gapped) ---
    coverage_md = ""
    if coverage_gaps:
        coverage_md = ("## 📁 Holdings coverage\n\n"
                       + "\n".join(f"- {g}" for g in coverage_gaps)
                       + "\n\n")

    # Disclosures lead — they are the product; the scorecard supports.
    markdown = (
        f"_{DISCLAIMER}_\n\n"
        f"{disclosures_md}\n{scorecard}\n\n{signals_md}{coverage_md}"
        f"---\n_Full tracker: [Featured stocks & trades]({TRACKER_URL})._"
    )

    # --- HTML email body (hand-authored, bulletproof template) ---
    date_label = date.fromisoformat(today_iso).strftime("%A, %B %-d, %Y")
    preheader = (
        f"{len(window)} new disclosures · {len(rows)} featured reads · "
        f"{len(sig_lines) + len(flips)} overnight changes")
    _email_kw = dict(
        date_label=date_label, disclaimer=DISCLAIMER, scorecard=sc_rows,
        signals=sig_data, flips=flip_data, disclosures=disc_data,
        extra_disclosures=max(0, len(recent) - MAX_DISCLOSURES), cutoff=cutoff,
        bond_count=bond_count,
        tracker_url=TRACKER_URL, preheader=preheader,
        report_url=report_url(today_iso),
        coverage=coverage_gaps or [])
    # Two renderings of the same email. `html` is a complete document, for the
    # SMTP copy where we are the sender. `html_embed` is just the card, for a
    # newsletter provider that wraps content in its own template — handing one
    # a full document nests two HTML documents and mangles the styling, and its
    # footer already carries a real unsubscribe link so ours is dropped.
    html = email_template.render_html(**_email_kw)
    html_embed = email_template.render_html(**_email_kw, standalone=False)

    counts = {"tickers": len(rows), "new_signals": len(sig_lines),
              "flips": len(flips), "disclosures": len(window),
              "bonds": bond_count}
    # The /report page renders from this same structure, so the web version and
    # the email can never drift. The page is the WHOLE undivided picture —
    # every filing in the window, bonds included; the email shows stock/option
    # rows (capped at MAX_DISCLOSURES because clients clip long messages) and
    # collapses bonds to a count that links here.
    payload = {
        "date": today_iso,
        "dateLabel": date_label,
        "cutoff": cutoff,
        "counts": counts,
        "scorecard": sc_rows,
        "signals": sig_data,
        "flips": flip_data,
        "disclosures": [{
            "filingDate": t.get("filing_date", "?"),
            "txDate": t.get("tx_date"),
            "member": t.get("member", "?"),
            "party": PARTY.get(t.get("party")),
            "ticker": t.get("ticker"),
            "asset": t.get("asset"),
            "type": t.get("type", "?"),
            "amount": t.get("amount_label", "—"),
            "sourceUrl": t.get("source_url"),
        } for t in window],
        "bondCount": bond_count,
        "emailShown": len(disc_data),
    }
    return {"markdown": markdown, "html": html, "html_embed": html_embed,
            "ratings": ratings, "counts": counts, "payload": payload}


def market_date(ai_tickers: dict) -> str:
    """The latest daily close behind the scorecard ("" when there is none).

    Every ticker carries the date of its last bar, so the maximum is the last
    session the readings describe. It stops advancing whenever the market is
    shut — the weekend, a holiday, or a price-source outage."""
    dates = [t.get("asof_date") for t in (ai_tickers or {}).values()
             if t.get("asof_date")]
    return max(dates) if dates else ""


def fingerprint(trades: list[dict], ai_tickers: dict) -> dict:
    """What today's report is made of, in three comparable values.

    ``trades_total`` only ever grows as filings arrive, so it does not fall
    when the disclosure window slides forward on a quiet day.
    ``last_filing_date`` catches a re-parse that replaces rows without
    changing the count."""
    return {
        "market_date": market_date(ai_tickers),
        "trades_total": len(trades),
        "last_filing_date": max((t.get("filing_date") or "") for t in trades)
        if trades else "",
    }


def whats_new(state: dict, now: dict) -> list[str]:
    """Why today's report is worth sending. An empty list means: do not send.

    The market closes at the weekend and on holidays, so a Sunday email
    repeats Saturday's word for word — the same closes, the same tally, the
    same rows. Two questions decide it: did the market print a new close, and
    did a new disclosure arrive. Signals and rating flips need no test of
    their own: both come from the indicators, so a signal implies a new close
    and the first question already caught it. Testing them separately would
    re-send yesterday's signals on a stale file and defeat the skip.

    A missing baseline always sends. The report must never go quiet because
    the record of the last one is absent."""
    if not state.get("date") or "market_date" not in state:
        return ["first run"]
    news = []
    if now["market_date"] and now["market_date"] != state.get("market_date"):
        news.append(f"new market close ({now['market_date']})")
    added = now["trades_total"] - (state.get("trades_total") or 0)
    if added > 0:
        news.append(f"{added} newly disclosed trade"
                    f"{'s' if added != 1 else ''}")
    elif (now["trades_total"] != state.get("trades_total")
          or now["last_filing_date"] != state.get("last_filing_date")):
        news.append("the disclosure record changed")
    return news


def build_traffic_email(traffic: dict, today_iso: str,
                        member_names: dict | None = None) -> dict:
    """Compose the standalone site-traffic email (subject, markdown, html) from
    a ``analytics.daily_summary`` dict. Pure — no I/O."""
    md, _ = analytics.format_block(traffic, member_names)
    markdown = (f"{md}\n\n---\n_Aggregated, cookieless Vercel Web Analytics · "
                f"[Capitol Ledger tracker]({TRACKER_URL})._")
    date_label = date.fromisoformat(today_iso).strftime("%A, %B %-d, %Y")
    total = traffic.get("total")
    days = traffic.get("windowDays", 7)
    preheader = (f"{total:,} page views" if total is not None
                 else "site traffic") + f" · last {days} days"
    html = email_template.render_traffic_html(
        date_label=date_label, traffic=traffic, member_names=member_names,
        tracker_url=TRACKER_URL, preheader=preheader)
    return {"subject": f"📈 Traffic report — {today_iso}",
            "markdown": markdown, "html": html}


# --- GitHub API (network) ------------------------------------------------

def _gh(method: str, url: str, token: str, payload: dict | None = None):
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    req = urllib.request.Request(url, data=data, method=method, headers={
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "crush-monitoring-morning-report",
        "Content-Type": "application/json",
    })
    with urllib.request.urlopen(req, timeout=30) as resp:
        body = resp.read().decode("utf-8")
        return resp.status, (json.loads(body) if body else {})


# --- Email (SMTP, stdlib) ------------------------------------------------

def send_email(subject: str, text_body: str, html_body: str) -> bool:
    """Send the report by SMTP if creds are configured, else no-op.

    Reads SMTP_USER / SMTP_PASS (required), SMTP_HOST (default smtp.gmail.com),
    SMTP_PORT (default 587 STARTTLS; 465 → implicit SSL), REPORT_EMAIL_TO
    (default = SMTP_USER) and REPORT_EMAIL_FROM (default = SMTP_USER — set it
    to send as a verified brand address while logging in as another account;
    it must be an address the SMTP host is authorised to send for, or SPF/DKIM
    alignment fails and the mail lands in spam). Best-effort: returns False and warns on any failure
    so a mail outage never fails the refresh. Credentials come only from env
    (GitHub secrets) and are never logged.
    """
    user = os.environ.get("SMTP_USER", "").strip()
    password = os.environ.get("SMTP_PASS", "").strip()
    if not user or not password:
        print("SMTP_USER/SMTP_PASS not set — skipping email (issue still posted)")
        return False
    # GitHub renders undefined `vars.*` as empty strings, so fall back with `or`.
    host = os.environ.get("SMTP_HOST", "").strip() or "smtp.gmail.com"
    port = int(os.environ.get("SMTP_PORT", "").strip() or "587")
    to_addr = os.environ.get("REPORT_EMAIL_TO", "").strip() or user
    # The From address can differ from the SMTP login: with a verified sending
    # domain you often authenticate as one account (a Gmail App Password, say)
    # but want the mail to come from the brand. Defaults to the login, which is
    # always a safe, aligned choice.
    from_addr = os.environ.get("REPORT_EMAIL_FROM", "").strip() or user

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg.set_content(text_body)
    msg.add_alternative(html_body, subtype="html")
    try:
        if port == 465:
            with smtplib.SMTP_SSL(host, port, context=ssl.create_default_context(),
                                  timeout=30) as s:
                s.login(user, password)
                s.send_message(msg)
        else:
            with smtplib.SMTP(host, port, timeout=30) as s:
                s.starttls(context=ssl.create_default_context())
                s.login(user, password)
                s.send_message(msg)
    except Exception as exc:  # noqa: BLE001 — best-effort, never fatal
        print(f"::warning::report email failed: {type(exc).__name__}")
        return False
    print(f"emailed report to {to_addr}")
    return True


_GENERATED = ("Generated by congress/daily_report.py (daily Action). "
              "Do not edit by hand.")


def write_web_edition(payload: dict) -> None:
    """Publish the always-current web edition read by /report.

    This runs on a quiet day too. The page keeps showing the latest picture
    even when no email goes out — a reader who opens /report on a Sunday must
    not find Friday's date on it."""
    try:
        REPORT_JSON.parent.mkdir(parents=True, exist_ok=True)
        REPORT_JSON.write_text(
            json.dumps({"_comment": _GENERATED, **payload},
                       indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8")
        print(f"wrote {REPORT_JSON.name} "
              f"({len(payload['disclosures'])} disclosures)")
    except OSError as exc:
        print(f"::warning::could not write report.json: {exc}")


def archive_report(payload: dict, counts: dict, today_iso: str) -> None:
    """Write the dated copy + the archive index for /report/<date>.

    Only a report that was delivered gets a permalink. A skipped day writes
    nothing here, so the archive lists the editions that went out and never
    an empty page an email never linked."""
    try:
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        # The same payload as report.json, so the permalink and the email can
        # never disagree about what went out.
        (REPORTS_DIR / f"{today_iso}.json").write_text(
            json.dumps({"_comment": _GENERATED, **payload},
                       indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8")
        index_path = REPORTS_DIR / "_index.json"
        index = _load(index_path, {}).get("reports", [])
        entry = {"date": today_iso, "dateLabel": payload["dateLabel"],
                 "counts": counts}
        index = [entry] + [e for e in index if e.get("date") != today_iso]
        index.sort(key=lambda e: e.get("date") or "", reverse=True)
        index_path.write_text(
            json.dumps({"_comment": _GENERATED, "reports": index},
                       indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8")
        print(f"archived report {today_iso} ({len(index)} in the archive)")
    except OSError as exc:
        print(f"::warning::could not archive the report: {exc}")


def main() -> int:
    repo = os.environ.get("REPO") or os.environ.get("GITHUB_REPOSITORY", "")
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN", "")
    if not repo or not token:
        print("no REPO / token — skipping morning report")
        return 0

    state = _load(STATE_JSON, {})
    today_iso = datetime.now(timezone.utc).date().isoformat()
    force = os.environ.get("REPORT_FORCE", "").strip().lower() in ("1", "true", "yes")
    # Idempotent per day: if a report was already posted today (e.g. an early
    # cron already ran), don't post a second — UNLESS forced (an explicit
    # on-demand send, which should always deliver).
    if not force and state.get("date") == today_iso and state.get("issue_number"):
        print(f"report already posted today (#{state['issue_number']}); skipping")
        return 0

    trades = _load(TRADES_JSON, {}).get("trades", [])
    ai = _load(AI_JSON, {})
    ai_tickers = ai.get("tickers", {})
    new_signals = ai.get("meta", {}).get("new_signals", [])
    prev_ratings = state.get("ratings", {})

    # Deep-link the email's tickers into their public pages (UTM-tagged).
    ticker_urls = ticker_links(_load(TICKER_INDEX_JSON, {}))
    gaps = holdings_gaps(_load(HOLDINGS_JSON, {}))
    report = build_report(trades, ai_tickers, new_signals, prev_ratings,
                          today_iso, ticker_urls=ticker_urls,
                          coverage_gaps=gaps)
    title = f"📋 Morning report — {today_iso}"

    # A quiet day: the market printed no new close and no filing arrived, so
    # this email would repeat yesterday's word for word. Skip every delivery —
    # the digest, the subscriber broadcast, the traffic email and the issue —
    # but still publish the web edition, so /report stays current. Nothing is
    # recorded in the state either: the fingerprint keeps describing the last
    # report that actually went out, and a later cron re-asks the question.
    now = fingerprint(trades, ai_tickers)
    news = whats_new(state, now)
    if not news and not force:
        print("nothing new since the last report (market closed, no new "
              "filings) — skipping the send")
        write_web_edition(report["payload"])
        return 0
    print("sending: " + ("; ".join(news) if news else "forced"))

    # Primary delivery: direct email via SMTP (reliable regardless of GitHub
    # notification settings). Best-effort — no-op if creds aren't configured.
    email_ok = send_email(title, report["markdown"], report["html"])

    # Subscribers: the same HTML, broadcast via Buttondown (which owns the
    # list, double opt-in and unsubscribe). Gated on BUTTONDOWN_API_KEY and
    # non-fatal — the owner's copy above must land either way. Runs inside the
    # per-day idempotency gate, so subscribers can't be double-sent.
    buttondown.send(title, report["html_embed"])

    # Site traffic (Vercel Web Analytics) ships as its OWN email so the digest
    # stays focused on trades. Non-fatal; None unless VERCEL_TOKEN +
    # VERCEL_PROJECT_ID are set, so the run never fails on analytics.
    traffic = analytics.daily_summary(today_iso)
    if traffic:
        # Real names for the member-page breakdown (slug → display name).
        member_names = {m["slug"]: m["name"]
                        for m in _load(MEMBER_INDEX_JSON, {}).get("members", [])}
        tr = build_traffic_email(traffic, today_iso, member_names)
        send_email(tr["subject"], tr["markdown"], tr["html"])

    # Secondary: a dated GitHub issue as an archive + the flip-diff state. Also
    # assign it to the repo owner (override REPORT_ASSIGNEE) so watchers/owners
    # are notified there too. Best-effort — a failure here must not lose state.
    assignee = os.environ.get("REPORT_ASSIGNEE") or repo.split("/")[0]
    new_number = None
    try:
        status, issue = _gh("POST", f"{API}/repos/{repo}/issues", token,
                            {"title": title, "body": report["markdown"],
                             "assignees": [assignee] if assignee else []})
        if 200 <= status < 300:
            new_number = issue.get("number")
            print(f"opened report issue #{new_number} ({report['counts']})")
        else:
            print(f"::warning::report issue POST returned {status}")
    except (urllib.error.HTTPError, urllib.error.URLError, OSError) as exc:
        print(f"::warning::report issue POST failed: {exc}")

    # Close yesterday's report issue so the list stays tidy (best-effort).
    prev_number = state.get("issue_number")
    if new_number and prev_number and prev_number != new_number:
        try:
            _gh("PATCH", f"{API}/repos/{repo}/issues/{prev_number}", token,
                {"state": "closed"})
            print(f"closed prior report issue #{prev_number}")
        except Exception as exc:  # noqa: BLE001 — best-effort
            print(f"::warning::could not close #{prev_number}: {exc}")

    if not (email_ok or new_number):
        # Nothing was delivered — don't record today as done, so the next run
        # retries rather than the idempotency gate skipping it.
        print("::warning::neither email nor issue delivered — not recording state")
        return 0
    # Publish the web version of this report for /report and archive the dated
    # copy (both committed by the Action). Best-effort: a write failure must
    # not lose the delivery state recorded below.
    write_web_edition(report["payload"])
    archive_report(report["payload"], report["counts"], today_iso)

    STATE_JSON.write_text(
        json.dumps({"date": today_iso,
                    "issue_number": new_number or state.get("issue_number"),
                    "ratings": report["ratings"],
                    **now},
                   separators=(",", ":"), ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
