"""Generate the Capitol Gains landing page's data files from real trades.

The landing site (``landing/``) renders these data files, regenerated by the
daily Action so every number on the page is a true statement about official
disclosures (see landing/docs/adr/0001):

- ``disclosures.json`` — the "Recent disclosures" feed: five real
  disclosures from a trailing window of filings, distinct members, chosen
  for variety (see CONTEXT.md: a curated window, never the literal five
  latest). Soft constraints: include at least one late filing if the window
  has one, and at least one BUY and one SELL; ranked by amount then
  recency; displayed chronologically.
- ``stats.json`` — the stats strip, year-scoped ("this year" = trade dates
  in the current calendar year): trades tracked, estimated disclosed volume
  (bracket midpoints), and the share of filings that arrived late.
- ``late.json`` — the /late leaderboard: the year's worst filing delays
  (filings that ARRIVED this year, ranked by days past the statutory
  maximum), one row per member (their worst filing) so a single batch
  filer cannot flood the board, plus each member's total late filings
  this year.

"Late" means past the STOCK Act's 45-day statutory maximum
(``daysLate = max(0, (filing_date - tx_date) - 45)``) — see
landing/docs/adr/0002 and landing/CONTEXT.md. Pure stdlib; the maths and
selection are fixture-tested offline.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

FEED_SIZE = 5
STATUTORY_MAX_DAYS = 45
# Widen the window until enough distinct members exist (quiet weeks happen).
WINDOW_STEPS_DAYS = (30, 60, 90, 180, 3650)

# Name suffixes that must not be mistaken for surnames ("James Hill III").
_SUFFIXES = {"jr", "jr.", "sr", "sr.", "ii", "iii", "iv", "v", "md", "m.d."}


def display_name(member: str) -> str:
    """"Nancy Pelosi" → "N. Pelosi"; suffix-safe ("Gilbert Cisneros, Jr." → "G. Cisneros")."""
    parts = [p.strip(",") for p in member.split()]
    parts = [p for p in parts if p and p.lower() not in _SUFFIXES]
    if len(parts) < 2:
        return member
    return f"{parts[0][0]}. {parts[-1]}"


def days_late(t: dict) -> int | None:
    """Days past the 45-day statutory maximum; 0 = on time; None = undatable."""
    fd, td = t.get("filing_date"), t.get("tx_date")
    if not fd or not td:
        return None
    try:
        gap = (date.fromisoformat(fd) - date.fromisoformat(td)).days
    except ValueError:
        return None
    return max(0, gap - STATUTORY_MAX_DAYS)


def _mid(t: dict) -> float:
    lo, hi = t.get("amount_lo"), t.get("amount_hi")
    if lo is None:
        return 0.0
    return (lo + (hi if hi is not None else lo)) / 2


def compact_bucket(lo, hi) -> str:
    """"$1M – $5M" / "$15K – $50K" per the prototype's compact style."""
    def one(x):
        if x >= 1_000_000:
            return f"${round(x / 1_000_000)}M"
        if x >= 1_000:
            return f"${round(x / 1_000)}K"
        return f"${x:,.0f}"
    if lo is None:
        return "—"
    if hi is None:
        return f"{one(lo)}+"
    return f"{one(lo)} – {one(hi)}"


def _eligible(trades: list[dict]) -> list[dict]:
    return [
        t for t in trades
        if t.get("ticker") and t.get("type") in ("buy", "sell")
        and days_late(t) is not None
    ]


def select_feed(trades: list[dict], count: int = FEED_SIZE) -> list[dict]:
    """Pick the feed rows: distinct members, variety-constrained (see module doc)."""
    pool = _eligible(trades)
    if not pool:
        return []
    latest = max(t["filing_date"] for t in pool)
    latest_d = date.fromisoformat(latest)

    window: list[dict] = []
    for step in WINDOW_STEPS_DAYS:
        window = [
            t for t in pool
            if (latest_d - date.fromisoformat(t["filing_date"])).days <= step
        ]
        if len({t["member"] for t in window}) >= count:
            break

    # Rank all window rows by size, then recency; first row per member wins.
    ranked = sorted(
        window,
        key=lambda t: (t.get("amount_lo") or 0, t["filing_date"], t.get("id", "")),
        reverse=True,
    )
    picked: list[dict] = []
    members: set[str] = set()
    for t in ranked:
        if t["member"] not in members:
            picked.append(t)
            members.add(t["member"])
        if len(picked) == count:
            break

    def ensure(predicate) -> None:
        """If no picked row satisfies ``predicate`` but the window has one,
        swap it in — replacing its member's own pick, else the lowest pick."""
        if any(predicate(t) for t in picked) or not picked:
            return
        for t in ranked:
            if not predicate(t):
                continue
            same = next((p for p in picked if p["member"] == t["member"]), None)
            picked[picked.index(same) if same else -1] = t
            return

    ensure(lambda t: (days_late(t) or 0) > 0)   # signature accusation, if true
    ensure(lambda t: t["type"] == "buy")
    ensure(lambda t: t["type"] == "sell")

    # Display order is chronological (newest filing first).
    picked.sort(key=lambda t: (t["filing_date"], t.get("tx_date", "")), reverse=True)
    return picked


def feed_payload(trades: list[dict]) -> list[dict]:
    """FR-2-shaped rows for landing/src/data/disclosures.json."""
    rows = []
    for t in select_feed(trades):
        chamber = "Senate" if t.get("chamber") == "senate" else "House"
        district = t.get("district") or t.get("state") or ""
        rows.append({
            "member": display_name(t["member"]),
            "chamber": chamber,
            "district": district,
            "ticker": t["ticker"],
            "side": t["type"].upper(),
            "amountBucket": compact_bucket(t.get("amount_lo"), t.get("amount_hi")),
            "filedDaysLate": days_late(t),
        })
    return rows


def stats_payload(trades: list[dict], today: date) -> dict:
    """Year-scoped stats, each stat scoped by its own noun: trades/volume by
    TRADE date this year; the late share by FILING date this year. Scoping the
    late share by trade year would undercount structurally — this year's
    trades haven't had time to become late yet (a June trade can only show as
    late from August onward)."""
    year = str(today.year)
    dated = [t for t in trades if days_late(t) is not None]
    traded_this_year = [t for t in dated if (t.get("tx_date") or "").startswith(year)]
    filed_this_year = [t for t in dated if (t.get("filing_date") or "").startswith(year)]
    late = sum(1 for t in filed_this_year if days_late(t) > 0)
    lags = sorted(
        (date.fromisoformat(t["filing_date"]) - date.fromisoformat(t["tx_date"])).days
        for t in traded_this_year
    )
    return {
        "year": today.year,
        "tradesThisYear": len(traded_this_year),
        "estVolumeThisYearUsd": round(sum(_mid(t) for t in traded_this_year)),
        "pctFiledLate": round(100 * late / len(filed_this_year)) if filed_this_year else 0,
        # The product's core tension: how long the public normally waits
        # between a trade happening and learning about it.
        "medianLagDays": lags[len(lags) // 2] if lags else 0,
    }


LATE_BOARD_SIZE = 10


def late_payload(trades: list[dict], today: date, count: int = LATE_BOARD_SIZE) -> dict:
    """The /late leaderboard: worst delays among filings that arrived this
    year (filing-year scope, same reasoning as ``pctFiledLate``), one row per
    member — their single worst filing — ranked by days late. ``lateCount``
    is that member's total number of late filings this year."""
    year = str(today.year)
    pool = [
        t for t in _eligible(trades)
        if (t.get("filing_date") or "").startswith(year) and days_late(t) > 0
    ]
    late_counts: dict[str, int] = {}
    worst: dict[str, dict] = {}
    for t in pool:
        m = t["member"]
        late_counts[m] = late_counts.get(m, 0) + 1
        w = worst.get(m)
        if w is None or (days_late(t), t["filing_date"]) > (days_late(w), w["filing_date"]):
            worst[m] = t
    ranked = sorted(
        worst.values(),
        key=lambda t: (days_late(t), t.get("amount_lo") or 0, t["filing_date"]),
        reverse=True,
    )[:count]
    rows = [{
        "member": display_name(t["member"]),
        "chamber": "Senate" if t.get("chamber") == "senate" else "House",
        "district": t.get("district") or t.get("state") or "",
        "ticker": t["ticker"],
        "side": t["type"].upper(),
        "amountBucket": compact_bucket(t.get("amount_lo"), t.get("amount_hi")),
        "daysLate": days_late(t),
        "tradeDate": t["tx_date"],
        "filedDate": t["filing_date"],
        "lateCount": late_counts[t["member"]],
    } for t in ranked]
    return {
        "year": today.year,
        "totalLateFilings": len(pool),
        "worst": rows,
    }


def write_files(trades: list[dict], out_dir: Path, today: date) -> tuple[int, dict]:
    """Write disclosures.json + stats.json + late.json; returns (rows, stats)
    for logging."""
    comment = (
        "Generated from real official disclosures by congress/landing_data.py "
        "(daily Action). Do not edit by hand. 'filedDaysLate' counts days past "
        "the STOCK Act's 45-day statutory maximum; 0 = on time."
    )
    rows = feed_payload(trades)
    stats = stats_payload(trades, today)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "disclosures.json").write_text(
        json.dumps({"_comment": comment, "disclosures": rows},
                   indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    (out_dir / "stats.json").write_text(
        json.dumps({"_comment": comment, **stats},
                   indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    (out_dir / "late.json").write_text(
        json.dumps({"_comment": comment, **late_payload(trades, today)},
                   indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return len(rows), stats
