"""Generate the Capitol Ledger landing page's data files from real trades.

The landing site (``landing/``) renders these data files, regenerated by the
daily Action so every number on the page is a true statement about official
disclosures (see landing/docs/adr/0001):

- ``disclosures.json`` — the "Recent disclosures" feed: five real
  disclosures from a trailing window of filings, distinct members, chosen
  for variety (see CONTEXT.md: a curated window, never the literal five
  latest). Soft constraints: include at least one late filing if the window
  has one, and at least one BUY and one SELL; ranked by amount then
  recency; displayed chronologically.
- ``stats.json`` — the stats strip, year-scoped ("this year" = trade dates
  in the current calendar year): trades tracked, estimated disclosed volume
  (bracket midpoints), and the share of filings that arrived late.
- ``late.json`` — the /late leaderboard: the year's worst filing delays
  (filings that ARRIVED this year, ranked by days past the statutory
  maximum), one row per member (their worst filing) so a single batch
  filer cannot flood the board, plus each member's total late filings
  this year.
- ``members/<slug>.json`` + ``members/_index.json`` — one page per
  featured filer (``MEMBER_PAGE_NAMES``): their WHOLE disclosed record
  (find-my-company needs every row in the HTML), most-traded tickers, filing-timeliness
  summary and estimated holdings (from the annual report). The /members
  index lists the set. Scaling this to every member is the storage-stage-1
  trigger in ROADMAP.md.

"Late" means past the STOCK Act's 45-day statutory maximum
(``daysLate = max(0, (filing_date - tx_date) - 45)``) — see
landing/docs/adr/0002 and landing/CONTEXT.md. Pure stdlib; the maths and
selection are fixture-tested offline.
"""

from __future__ import annotations

import json
import re
from collections import Counter
from datetime import date
from pathlib import Path

from . import sectors

FEED_SIZE = 5
STATUTORY_MAX_DAYS = 45
# Widen the window until enough distinct members exist (quiet weeks happen).
WINDOW_STEPS_DAYS = (30, 60, 90, 180, 3650)

# Name suffixes that must not be mistaken for surnames ("James Hill III").
_SUFFIXES = {"jr", "jr.", "sr", "sr.", "ii", "iii", "iv", "v", "md", "m.d."}


def display_name(member: str) -> str:
    """"Nancy Pelosi" → "N. Pelosi"; suffix-safe ("Gilbert Cisneros, Jr." → "G. Cisneros")."""
    parts = [p.strip(",") for p in member.split()]
    parts = [p for p in parts if p and p.lower() not in _SUFFIXES]
    if len(parts) < 2:
        return member
    return f"{parts[0][0]}. {parts[-1]}"


def days_late(t: dict) -> int | None:
    """Days past the 45-day statutory maximum; 0 = on time; None = undatable."""
    fd, td = t.get("filing_date"), t.get("tx_date")
    if not fd or not td:
        return None
    try:
        gap = (date.fromisoformat(fd) - date.fromisoformat(td)).days
    except ValueError:
        return None
    return max(0, gap - STATUTORY_MAX_DAYS)


def _mid(t: dict) -> float:
    lo, hi = t.get("amount_lo"), t.get("amount_hi")
    if lo is None:
        return 0.0
    return (lo + (hi if hi is not None else lo)) / 2


def compact_bucket(lo, hi) -> str:
    """"$1M – $5M" / "$15K – $50K" per the prototype's compact style."""
    def one(x):
        if x >= 1_000_000:
            return f"${round(x / 1_000_000)}M"
        if x >= 1_000:
            return f"${round(x / 1_000)}K"
        return f"${x:,.0f}"
    if lo is None:
        return "—"
    if hi is None:
        return f"{one(lo)}+"
    return f"{one(lo)} – {one(hi)}"


def money(x: float) -> str:
    """A single point-estimate dollar amount, compact: "$5.0M" / "$250K"."""
    x = max(0.0, x)
    if x >= 1_000_000:
        return f"${x / 1_000_000:.1f}M"
    if x >= 1_000:
        return f"${round(x / 1_000)}K"
    return f"${x:,.0f}"


def _holding_mid(h: dict) -> float:
    """Bracket-midpoint value of one annual-report holding (floor if open-ended)."""
    lo, hi = h.get("value_lo"), h.get("value_hi")
    if lo is None:
        return 0.0
    return (lo + (hi if hi is not None else lo)) / 2


def _is_option_trade(t: dict) -> bool:
    """True when the row IS an option position, not merely one that mentions
    an option.

    An **exercise** is the case that matters: it is filed as ``asset_type
    "Stock"`` and still carries the ``option`` sub-object describing the
    contract it converted. Testing that key routed those rows into the option
    pass, which then dropped them for having no expiry left, so Pelosi's
    5,000 exercised VST shares appeared in neither list — six exercise rows
    were lost this way. The free-text parser also attaches ``{"type":
    "call"}`` to a hedge-fund "Capital call of $3,723.39", which is not an
    option at all.

    ``asset_type`` is the field the pipeline sets deliberately, so it decides.
    """
    return t.get("asset_type") == "Option"


def _eligible(trades: list[dict]) -> list[dict]:
    return [
        t for t in trades
        if t.get("ticker") and t.get("type") in ("buy", "sell")
        and days_late(t) is not None
    ]


def select_feed(trades: list[dict], count: int = FEED_SIZE) -> list[dict]:
    """Pick the feed rows: distinct members, variety-constrained (see module doc)."""
    pool = _eligible(trades)
    if not pool:
        return []
    latest = max(t["filing_date"] for t in pool)
    latest_d = date.fromisoformat(latest)

    window: list[dict] = []
    for step in WINDOW_STEPS_DAYS:
        window = [
            t for t in pool
            if (latest_d - date.fromisoformat(t["filing_date"])).days <= step
        ]
        if len({t["member"] for t in window}) >= count:
            break

    # Rank all window rows by size, then recency; first row per member wins.
    ranked = sorted(
        window,
        key=lambda t: (t.get("amount_lo") or 0, t["filing_date"], t.get("id", "")),
        reverse=True,
    )
    picked: list[dict] = []
    members: set[str] = set()
    for t in ranked:
        if t["member"] not in members:
            picked.append(t)
            members.add(t["member"])
        if len(picked) == count:
            break

    def ensure(predicate) -> None:
        """If no picked row satisfies ``predicate`` but the window has one,
        swap it in — replacing its member's own pick, else the lowest pick."""
        if any(predicate(t) for t in picked) or not picked:
            return
        for t in ranked:
            if not predicate(t):
                continue
            same = next((p for p in picked if p["member"] == t["member"]), None)
            picked[picked.index(same) if same else -1] = t
            return

    ensure(lambda t: (days_late(t) or 0) > 0)   # signature accusation, if true
    ensure(lambda t: t["type"] == "buy")
    ensure(lambda t: t["type"] == "sell")

    # Display order is chronological (newest filing first).
    picked.sort(key=lambda t: (t["filing_date"], t.get("tx_date", "")), reverse=True)
    return picked


def feed_payload(trades: list[dict],
                 ticker_pages: set[str] | None = None) -> list[dict]:
    """FR-2-shaped rows for landing/src/data/disclosures.json.

    ``memberSlug``/``tickerSlug`` are set only when the corresponding page
    exists (featured member set / the ticker-page universe), so the feed can
    deep-link without ever minting a dead link. The display name is
    abbreviated ("N. Pelosi"), which is why the slug is derived from the full
    filer name here, where it is still known."""
    ticker_pages = ticker_pages or set()
    featured = set(MEMBER_PAGE_NAMES)
    rows = []
    for t in select_feed(trades):
        chamber = "Senate" if t.get("chamber") == "senate" else "House"
        district = t.get("district") or t.get("state") or ""
        rows.append({
            "member": display_name(t["member"]),
            "memberSlug": (
                slugify(t["member"]) if t["member"] in featured else None
            ),
            "chamber": chamber,
            "district": district,
            "ticker": t["ticker"],
            "tickerSlug": (
                ticker_slug(t["ticker"]) if t["ticker"] in ticker_pages
                else None
            ),
            "side": t["type"].upper(),
            "amountBucket": compact_bucket(t.get("amount_lo"), t.get("amount_hi")),
            "filedDaysLate": days_late(t),
        })
    return rows


# Debt instruments filed without a ticker — kept in the record and on member
# pages (they are real disclosures; Trump's filings are ALL bonds), but out of
# the HEADLINE stats: the product's story is stock trading, and other trackers
# don't count bonds, so a bond-inflated hero number reads as overcounting.
_BOND_ASSET_TYPES = frozenset({
    "bond", "Corporate Bond", "Municipal Security", "Government Security",
    "Corporate Security",  # House code CS: corporate bonds and notes
})


def is_bond(t: dict) -> bool:
    return not t.get("ticker") and t.get("asset_type") in _BOND_ASSET_TYPES


def stats_payload(trades: list[dict], today: date) -> dict:
    """Year-scoped stats, each stat scoped by its own noun: trades/volume by
    TRADE date this year; the late share by FILING date this year. Scoping the
    late share by trade year would undercount structurally — this year's
    trades haven't had time to become late yet (a June trade can only show as
    late from August onward). Ticker-less bond rows stay out of every number
    here (see ``is_bond``) — the copy above these stats says "stock trades",
    so the numbers must count exactly that."""
    year = str(today.year)
    dated = [t for t in trades
             if days_late(t) is not None and not is_bond(t)]
    traded_this_year = [t for t in dated if (t.get("tx_date") or "").startswith(year)]
    filed_this_year = [t for t in dated if (t.get("filing_date") or "").startswith(year)]
    late = sum(1 for t in filed_this_year if days_late(t) > 0)
    lags = sorted(
        (date.fromisoformat(t["filing_date"]) - date.fromisoformat(t["tx_date"])).days
        for t in traded_this_year
    )
    return {
        "year": today.year,
        "tradesThisYear": len(traded_this_year),
        "estVolumeThisYearUsd": round(sum(_mid(t) for t in traded_this_year)),
        "pctFiledLate": round(100 * late / len(filed_this_year)) if filed_this_year else 0,
        # The product's core tension: how long the public normally waits
        # between a trade happening and learning about it.
        "medianLagDays": lags[len(lags) // 2] if lags else 0,
    }


LATE_BOARD_SIZE = 10


def late_payload(trades: list[dict], today: date, count: int = LATE_BOARD_SIZE) -> dict:
    """The /late leaderboard: worst delays among filings that arrived this
    year (filing-year scope, same reasoning as ``pctFiledLate``), one row per
    member — their single worst filing — ranked by days late. ``lateCount``
    is that member's total number of late filings this year."""
    year = str(today.year)
    pool = [
        t for t in _eligible(trades)
        if (t.get("filing_date") or "").startswith(year) and days_late(t) > 0
    ]
    late_counts: dict[str, int] = {}
    worst: dict[str, dict] = {}
    for t in pool:
        m = t["member"]
        late_counts[m] = late_counts.get(m, 0) + 1
        w = worst.get(m)
        if w is None or (days_late(t), t["filing_date"]) > (days_late(w), w["filing_date"]):
            worst[m] = t
    ranked = sorted(
        worst.values(),
        key=lambda t: (days_late(t), t.get("amount_lo") or 0, t["filing_date"]),
        reverse=True,
    )[:count]
    rows = [{
        "member": display_name(t["member"]),
        "chamber": "Senate" if t.get("chamber") == "senate" else "House",
        "district": t.get("district") or t.get("state") or "",
        "ticker": t["ticker"],
        "side": t["type"].upper(),
        "amountBucket": compact_bucket(t.get("amount_lo"), t.get("amount_hi")),
        "daysLate": days_late(t),
        "tradeDate": t["tx_date"],
        "filedDate": t["filing_date"],
        "lateCount": late_counts[t["member"]],
    } for t in ranked]
    return {
        "year": today.year,
        "totalLateFilings": len(pool),
        "worst": rows,
    }


# Featured filers that get their own /members/<slug> page. A curated SEO set
# (highest-intent search names with enough disclosed trades to fill a page),
# NOT the full tracker watchlist in featured.json. Scaling to every member is
# the storage-stage-1 trigger in ROADMAP.md; keep this small until then.
MEMBER_PAGE_NAMES = [
    "Nancy Pelosi",
    "Donald J. Trump",
    "Marjorie Taylor Greene",
    "Tommy Tuberville",
    "Josh Gottheimer",
    "Cleo Fields",
    "Gilbert Ray Cisneros, Jr.",
    "Alan Armstrong",
    "David McCormick",
    "April McClain Delaney",
    "John J. McGuire III",
]
# Member pages ship the member's WHOLE disclosed record (owner request,
# 2026-08-23): the page's job is find-my-company, and a filter over a
# truncated list lies — the row someone searches for must be in the HTML.
# The page collapses long tables client-side instead of capping the data.
MEMBER_HOLDINGS_CAP = 16


def slugify(name: str) -> str:
    """"Nancy Pelosi" → "nancy-pelosi" (URL slug for /members/<slug>)."""
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def _side_label(t: dict) -> str:
    return {"buy": "BUY", "sell": "SELL"}.get(t.get("type"), (t.get("type") or "").upper())


def rolled_holdings(member_trades: list[dict], h: dict, today_iso: str) -> dict:
    """Estimated CURRENT holdings — the member's latest annual snapshot rolled
    forward with every disclosed trade dated after it. This was a port of the
    tracker's JS ``rollForward``; that tab is gone, so this is now the only
    implementation:

    - stock buys add / sells subtract by bracket midpoint;
    - tickers first traded *after* the snapshot appear (flagged ``isNew``);
    - live options = snapshot options + EVERY disclosed option buy (not only
      those after the snapshot — see the comment at the option pass), minus
      any already expired (expiration < today) and any closed by a disclosed
      sale, deduped by (ticker, type, strike, expiry).

    Bracket midpoints, NOT share counts — a directional estimate. Returns
    ``{snap, filings, stocks, options}`` with dollar-midpoint ``est`` values."""
    # No machine-readable annual baseline → no holdings estimate (don't
    # fabricate positions from trades alone; the page just omits the section).
    if not h.get("available"):
        return {"snap": None, "filings": 0, "stocks": [], "options": []}
    stocks_in = h.get("stocks", [])
    # Annual reports value assets at year end; roll forward from there (fall
    # back to the filing date when the report year is unknown).
    snap = (f"{h['report_year']}-12-31" if h.get("report_year")
            else (h.get("filing_date") or "0000-00-00"))

    pos: dict = {}
    for s in stocks_in:
        if s.get("asset_type") != "Stock":
            continue
        k = s.get("ticker") or s.get("asset")
        pos[k] = {"ticker": s.get("ticker"), "asset": s.get("asset"),
                  "base": _holding_mid(s), "delta": 0.0, "inSnap": True}

    since = [t for t in member_trades if (t.get("tx_date") or "") > snap]
    # Options are swept from the WHOLE record, not just `since` — see the
    # comment on the option pass below.
    opt_trades = [t for t in member_trades if _is_option_trade(t)]
    filings = set()
    for t in since:
        if t.get("filing_id"):
            filings.add(t["filing_id"])
        if _is_option_trade(t):
            continue
        tk = t.get("ticker")
        if not tk:
            continue
        e = pos.get(tk)
        if e is None:
            e = {"ticker": tk, "asset": t.get("asset"), "base": 0.0,
                 "delta": 0.0, "inSnap": False}
            pos[tk] = e
        if t.get("type") == "buy":
            e["delta"] += _mid(t)
        elif t.get("type") == "sell":
            e["delta"] -= _mid(t)

    stocks = []
    for e in pos.values():
        est = max(0.0, e["base"] + e["delta"])
        if est <= 0:
            continue
        stocks.append({"ticker": e["ticker"] or "—", "asset": e["asset"] or "",
                       "est": est, "isNew": not e["inSnap"]})
    stocks.sort(key=lambda x: -x["est"])

    opt_map: dict = {}
    def _add_opt(ticker, opt, est):
        exp = (opt or {}).get("expiration")
        if not ticker or not exp or exp < today_iso:
            return
        key = (ticker, (opt.get("type") or ""), (opt.get("strike") or ""), exp)
        prev = opt_map.get(key)
        if prev is None:
            opt_map[key] = {"ticker": ticker, "type": opt.get("type"),
                            "strike": opt.get("strike"), "expiration": exp,
                            "est": est or 0.0}
        else:
            prev["est"] = max(prev["est"], est or 0.0)
    for s in stocks_in:
        if s.get("asset_type") == "Option":
            _add_opt(s.get("ticker"), s.get("option") or {}, _holding_mid(s))
    # EVERY disclosed option buy, not only those dated after the snapshot. An
    # option bought in the days BEFORE the snapshot belongs to the annual
    # report, so when that report's parser misses it the position exists in no
    # path at all and the page silently omits it: Pelosi's Jan-2027 calls were
    # bought 2025-12-30 against a 2025-12-31 snapshot, and AMZN, GOOGL and NVDA
    # vanished while AAPL survived only because the parser happened to catch
    # it. The dedup key makes the wider sweep safe — a contract present in both
    # the snapshot and the trades collapses to one entry.
    for t in opt_trades:
        if t.get("type") == "buy":
            _add_opt(t.get("ticker"), t.get("option") or {}, _mid(t))
    # A disclosed sale closes the position. Sales are rarer than purchases in
    # this record, so an option closed without one stays listed until it
    # expires — the estimate errs toward showing a position, never toward
    # inventing a strike.
    for t in opt_trades:
        if t.get("type") == "sell":
            o = t.get("option") or {}
            exp = o.get("expiration")
            if t.get("ticker") and exp:
                opt_map.pop(
                    (t["ticker"], o.get("type") or "", o.get("strike") or "",
                     exp), None)
    options = sorted(opt_map.values(), key=lambda x: -x["est"])

    return {"snap": snap, "filings": len(filings), "stocks": stocks,
            "options": options}


def member_payload(name: str, trades: list[dict], holdings: dict,
                   today_iso: str = "9999-12-31",
                   ticker_pages: set[str] | None = None,
                   returns: dict | None = None,
                   perf: dict | None = None,
                   committees: dict | None = None,
                   sector_data: dict | None = None) -> dict:
    """Per-member page data: summary, most-traded tickers, every disclosed
    trade (the page filters client-side), and estimated holdings from the
    member's annual report (``holdings`` is the ``holdings.json`` ``holdings``
    map, keyed by full member name). ``ticker_pages`` is the set of symbols
    that have a /tickers/<slug> page, so the chips can link there.
    ``returns`` is returns.json's id→record map and ``perf`` is
    performance.json — together they feed the trading-performance section."""
    has_ticker_page = ticker_pages or set()
    ts = [t for t in trades if t.get("member") == name]
    ts.sort(key=lambda t: (t.get("tx_date") or "", t.get("filing_date") or ""),
            reverse=True)
    ref = ts[0] if ts else {}

    tickers = Counter(t["ticker"] for t in ts if t.get("ticker"))
    asset_of: dict[str, str] = {}
    for t in ts:
        tk = t.get("ticker")
        if tk and tk not in asset_of:
            asset_of[tk] = t.get("asset") or tk

    dated = [t for t in ts if t.get("tx_date")]
    late_vals = [days_late(t) for t in ts if days_late(t) is not None]
    late_pos = [d for d in late_vals if d > 0]

    rows = [{
        "ticker": t.get("ticker") or "—",
        "asset": t.get("asset") or "",
        "side": _side_label(t),
        "amountBucket": compact_bucket(t.get("amount_lo"), t.get("amount_hi")),
        "txDate": t.get("tx_date"),
        "filedDate": t.get("filing_date"),
        "daysLate": days_late(t),
        "sourceUrl": t.get("source_url"),
        # Explicit, from the same predicate as the home-page stats: the
        # Assets filter must never guess bond-ness from a missing ticker
        # (an unresolved equity also lacks one).
        "bond": is_bond(t),
    } for t in ts]

    # Estimated CURRENT holdings: the annual snapshot rolled forward with every
    # trade filed since (so a recent buy/option that post-dates the annual
    # report shows up), mirroring the tracker. Bracket midpoints, not shares.
    h = holdings.get(name, {}) if holdings else {}
    rf = rolled_holdings(ts, h, today_iso)
    held = rf["stocks"]
    total_est = sum(x["est"] for x in held)
    holdings_block = {
        "available": bool(h.get("available")),
        "filingDate": h.get("filing_date"),
        "reportYear": h.get("report_year"),
        "snapDate": rf["snap"],
        "filingsSince": rf["filings"],
        "sourceUrl": h.get("source_url"),
        "totalLabel": money(total_est) if held else None,
        "positions": len(held),
        "stocks": [{
            "ticker": x["ticker"],
            "asset": x["asset"],
            "estLabel": money(x["est"]),
            "pctPortfolio": (
                round(100 * x["est"] / total_est, 1) if total_est else None
            ),
            "isNew": x["isNew"],
        } for x in held[:MEMBER_HOLDINGS_CAP]],
        "options": [{
            "ticker": o["ticker"],
            "type": o["type"],
            "strike": o["strike"],
            "expiration": o["expiration"],
            "estLabel": money(o["est"]),
        } for o in rf["options"][:MEMBER_HOLDINGS_CAP]],
    }

    return {
        "slug": slugify(name),
        "name": name,
        "party": ref.get("party"),
        "state": ref.get("state"),
        # Executive-branch filers (OGE 278-T, e.g. the President) are neither
        # House nor Senate — don't mislabel them as "House".
        "chamber": {"senate": "Senate", "executive": "Executive"}.get(
            ref.get("chamber"), "House"
        ),
        "district": ref.get("district"),
        "summary": {
            "trades": len(ts),
            "distinctTickers": len(tickers),
            "firstTx": min((t["tx_date"] for t in dated), default=None),
            "lastTx": max((t["tx_date"] for t in dated), default=None),
            # The page dateline's "newest filing" — how recent the newest
            # information here is, as opposed to when we last rebuilt the page.
            "lastFiling": max(
                (t["filing_date"] for t in ts if t.get("filing_date")),
                default=None),
            "pctLate": round(100 * len(late_pos) / len(late_vals)) if late_vals else 0,
            "worstLate": max(late_vals) if late_vals else 0,
        },
        "topTickers": [
            {"ticker": tk, "count": n, "asset": asset_of.get(tk, tk),
             "slug": ticker_slug(tk), "hasPage": tk in has_ticker_page}
            for tk, n in tickers.most_common(6)
        ],
        "trades": rows,
        "tradesShown": len(rows),
        "holdings": holdings_block,
        "performance": performance_block(name, ts, returns, perf),
        "committees": committee_block(name, committees, ts, sector_data),
    }


# Options and crypto have their own price dynamics; a "return since buy" of
# the underlying is not the position's return. Mirrors prices.NON_EQUITY.
PERF_NON_EQUITY = frozenset({"Option", "Cryptocurrency"})
# Below this many priced buys the numbers are one lucky pick wearing a
# median's clothes. Mirrors performance.MIN_PRICED_BUYS.
PERF_MIN_BUYS = 3
PERF_ROW_CAP = 12


def performance_block(name: str, member_trades: list[dict],
                      returns: dict | None, perf: dict | None) -> dict:
    """The trading-performance section's data: KPIs, per-buy rows with the
    S&P over the same window, and the $1-race series. ``available`` is False
    (with a reason) until there are enough priced buys AND the benchmark data
    exists — the page renders nothing rather than a two-buy 'track record'."""
    buys = [t for t in member_trades
            if t.get("type") == "buy" and t.get("ticker")
            and t.get("asset_type") not in PERF_NON_EQUITY]
    priced = []
    for t in buys:
        rec = (returns or {}).get(t.get("id"))
        if rec and rec.get("bench_pct") is not None:
            priced.append((t, rec))
    if len(priced) < PERF_MIN_BUYS:
        reason = ("no_benchmark" if buys and returns and not priced
                  else "not_enough_priced_buys")
        return {"available": False, "reason": reason,
                "pricedBuys": len(priced), "stockBuys": len(buys)}

    priced.sort(key=lambda pair: (pair[0].get("tx_date") or "",
                                  pair[0].get("id") or ""), reverse=True)
    pcts = sorted(rec["pct"] for _, rec in priced)
    bench_pcts = sorted(rec["bench_pct"] for _, rec in priced)
    beat = sum(1 for _, rec in priced if rec["pct"] > rec["bench_pct"])

    def _median(vals: list[float]) -> float:
        mid = len(vals) // 2
        if len(vals) % 2:
            return vals[mid]
        return round((vals[mid - 1] + vals[mid]) / 2, 1)

    series = (perf or {}).get("members", {}).get(name)
    bench_meta = (perf or {}).get("benchmark", {})
    return {
        "available": True,
        "benchLabel": bench_meta.get("label") or "S&P 500",
        "asofDate": bench_meta.get("asof_date"),
        "kpis": {
            "medianPct": _median(pcts),
            "medianBenchPct": _median(bench_pcts),
            "beat": beat,
            "beatOf": len(priced),
            "priced": len(priced),
            "pricedOf": len(buys),
        },
        "series": series,  # None → the page skips the chart, keeps the rest
        "rows": [{
            "ticker": t["ticker"],
            "txDate": t.get("tx_date"),
            "pct": rec["pct"],
            "benchPct": rec["bench_pct"],
            "excess": round(rec["pct"] - rec["bench_pct"], 1),
        } for t, rec in priced[:PERF_ROW_CAP]],
        "rowsOf": len(priced),
    }


def write_member_files(
    trades: list[dict], holdings: dict, out_dir: Path,
    names: list[str] = MEMBER_PAGE_NAMES,
    today_iso: str = "9999-12-31",
    returns: dict | None = None,
    perf: dict | None = None,
) -> list[str]:
    """Write members/<slug>.json for each featured filer with trades, plus
    members/_index.json. Members with no disclosed trades are skipped (an
    empty page is worse than none). ``today_iso`` drives options-expiry in the
    rolled-forward holdings. Returns the slugs written."""
    comment = (
        "Generated from real official disclosures by congress/landing_data.py "
        "(daily Action). Do not edit by hand."
    )
    members_dir = out_dir / "members"
    members_dir.mkdir(parents=True, exist_ok=True)
    # Which symbols have their own page — lets member chips link to them
    # (internal linking between the two page sets).
    ticker_pages = set(select_ticker_pages(trades))
    # Read once, not once per member: the file holds all 541 sitting members.
    committees = load_committees()
    sector_data = sectors.load()
    index = []
    written = []
    for name in names:
        payload = member_payload(name, trades, holdings, today_iso,
                                 ticker_pages, returns, perf, committees,
                                 sector_data)
        if payload["summary"]["trades"] == 0:
            continue
        (members_dir / f"{payload['slug']}.json").write_text(
            json.dumps({"_comment": comment, **payload},
                       indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        written.append(payload["slug"])
        # The $1-race totals, for the index card's performance line. Only
        # when the series exists — and ALWAYS as a pair: a member's number
        # without the index over the same windows reads as skill in what may
        # simply be a bull market. (Named pblock, NOT perf — reusing the
        # parameter name here once clobbered the shared performance file
        # after the first iteration, silently blanking every later member.)
        pblock = payload.get("performance") or {}
        series = pblock.get("series") if pblock.get("available") else None
        index.append({
            "slug": payload["slug"],
            "name": payload["name"],
            "party": payload["party"],
            "state": payload["state"],
            "chamber": payload["chamber"],
            "district": payload["district"],
            "trades": payload["summary"]["trades"],
            "pctLate": payload["summary"]["pctLate"],
            "worstLate": payload["summary"]["worstLate"],
            "perfPct": (round(series["member"][-1] - 100)
                        if series and series.get("member") else None),
            "perfBenchPct": (round(series["bench"][-1] - 100)
                             if series and series.get("bench") else None),
        })
    (members_dir / "_index.json").write_text(
        json.dumps({"_comment": comment, "members": index},
                   indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return written


# --- Ticker pages (/tickers/<symbol>) -----------------------------------
#
# Chosen by SUBSTANCE, not by the featured watchlist: the most-traded tickers
# in the real disclosure data: EVERY symbol clearing TICKER_PAGE_MIN_TRADES
# earns one. There is deliberately no top-N cap — a cap cut 66 symbols that
# met the substance bar (ORCL 47, IBM 45, LMT 25 …), which is a content gap,
# not SEO hygiene.
#
# Featured-watchlist names below the bar still get a page so the tracker's
# "See who traded it" link always resolves, but they are marked NOINDEX: the
# link works for a reader, and a 4-trade stub (NU) never enters the index.
# That is the standing "no thin indexable pages" rule, kept intact.
#
# Scaling to *every* ticker (1,399) remains the storage-stage-1 trigger in
# ROADMAP.md; this still slices the trades JSON in memory, like member pages.
TICKER_PAGE_MIN_TRADES = 25
TICKER_TRADE_CAP = 25
TICKER_MEMBER_CAP = 10

# Boilerplate the filings append to company names ("NVIDIA Corporation - Common
# Stock"); stripped so headings read like the company, not the filing.
_ASSET_NOISE = re.compile(
    r"\s*[-–]?\s*(class\s+[a-z]\s+)?(common\s+stock|capital\s+stock|"
    r"ordinary\s+shares?|common\s+shares?|stock|sponsored\s+adr|"
    r"unsponsored\s+adr|adr)\s*$",
    re.IGNORECASE,
)


def ticker_slug(ticker: str) -> str:
    """"BRK.B" → "brk-b" (URL slug for /tickers/<slug>)."""
    return re.sub(r"[^a-z0-9]+", "-", ticker.lower()).strip("-")


def clean_company(asset: str, ticker: str) -> str:
    """"NVIDIA Corporation - Common Stock" → "NVIDIA Corporation"."""
    name = (asset or "").strip()
    # Filings often trail the symbol in parens: "Apple Inc. (AAPL)".
    name = re.sub(r"\s*\(" + re.escape(ticker) + r"\)\s*$", "", name,
                  flags=re.IGNORECASE)
    prev = None
    while prev != name:               # peel repeated suffixes ("ADR Common Stock")
        prev = name
        name = _ASSET_NOISE.sub("", name).strip(" -–,")
    name = re.sub(r"\s*\(The\)\s*", " ", name).strip()
    return name or ticker


def featured_tickers() -> list[str]:
    """The watchlist shown on the tracker's "Featured stocks" tab. Those rows
    link out per ticker, so each one needs a page that resolves."""
    from .indicators import AI_TICKERS

    return [t["ticker"] for t in AI_TICKERS if t.get("ticker")]


def select_ticker_pages(trades: list[dict],
                        minimum: int = TICKER_PAGE_MIN_TRADES,
                        featured: list[str] | None = None) -> list[str]:
    """The ticker universe that earns a page, most-traded first.

    Two ways in: clearing `minimum` disclosed trades (indexable), or being on
    the featured watchlist (linked from the tracker, so it must resolve —
    noindex when thin; see `ticker_is_indexable`).
    """
    counts = Counter(t["ticker"] for t in trades if t.get("ticker"))
    picked = [tk for tk, n in counts.most_common() if n >= minimum]
    seen = set(picked)
    for tk in (featured if featured is not None else featured_tickers()):
        if tk and tk not in seen:
            picked.append(tk)
            seen.add(tk)
    return picked


# Derived from this file, not from `pipeline`: this module stays import-light
# and path-free by design so the tests run it in isolation.
AI_INDICATORS_PATH = (Path(__file__).resolve().parent.parent
                      / "docs" / "data" / "ai-indicators.json")


def load_indicators(path: Path = AI_INDICATORS_PATH) -> dict:
    """The featured-watchlist technical readings, keyed by ticker. Missing or
    unreadable → {}, so ticker pages simply omit the technical panel."""
    try:
        return json.loads(path.read_text(encoding="utf-8")).get("tickers", {})
    except (OSError, ValueError, AttributeError):
        return {}


COMMITTEES_PATH = (Path(__file__).resolve().parent.parent
                   / "docs" / "data" / "committees.json")


def load_committees(path: Path = COMMITTEES_PATH) -> dict:
    """The committee assignments written by `congress committees`. Missing or
    unreadable → an empty map, and every member page omits the block."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError, AttributeError):
        return {"members": {}}


def committee_block(name: str, data: dict | None,
                    trades: list[dict] | None = None,
                    sector_data: dict | None = None) -> dict | None:
    """A member's seats, for their page. None when there is nothing to show.

    It reports the seat and the trade, and it stops there. A committee beside
    a trade in the industry that committee oversees is a coincidence of two
    public facts. A claim that one caused the other is not, and this project
    does not make it. The reader sees both and decides.

    An empty list is not one thing (the `holdings.classify` rule again). A
    sitting member with no seats genuinely has none, a former member left
    Congress, and an executive filer has no committees at all. Only the first
    is worth stating on a page, so the other reasons return None instead of a
    puzzling blank heading.

    ``trades`` are that member's trades and ``sector_data`` the curated maps
    from `congress.sectors`. Given both, the block also lists the symbols the
    member disclosed in an industry one of their seats oversees, with the
    coverage counts, so the page can say how much of the trading our map
    classifies.
    """
    rec = (data or {}).get("members", {}).get(name)
    if not rec:
        return None
    seats = rec.get("committees") or []
    if not seats:
        return None
    block = {
        "reason": rec.get("reason"),
        "committees": [{
            "name": c.get("shortName") or c.get("name"),
            "url": c.get("url"),
            "title": c.get("title"),
            "subcommittees": [s.get("name") for s in c.get("subcommittees", [])
                              if s.get("name")],
        } for c in seats],
    }
    sd = sector_data or {}
    if not sd:
        return block
    grouped = sectors.classify(trades or [], sd)
    named = [{"id": c.get("id"), "name": c.get("shortName") or c.get("name")}
             for c in seats]
    rows = sectors.overlap(named, grouped, sd)
    if rows:
        block["overlap"] = rows
        block["coverage"] = {"classified": grouped["classified"],
                             "total": grouped["total"]}
    return block


def load_market(path: Path = AI_INDICATORS_PATH) -> dict | None:
    """The market-wide volatility reading (`congress.market`), or None.

    Written by the indicators run into the same file as the ticker readings.
    Missing or unreadable → None, and every surface omits the line."""
    try:
        return json.loads(path.read_text(encoding="utf-8")).get("market") or None
    except (OSError, ValueError, AttributeError):
        return None


def technical_block(ticker: str, readings: dict) -> dict | None:
    """The ticker page's "Technical read" panel: the SAME mechanical reading
    the tracker and the morning report show, scored by the SAME function
    (`indicators.ai_score`) so the three surfaces can never disagree.

    Descriptive only — a transparent tally of the indicators displayed, never
    advice. None for any ticker outside the featured watchlist.
    """
    rec = readings.get(ticker)
    if not rec:
        return None
    from .indicators import ai_score

    return {
        "asOf": rec.get("asof_date"),
        "price": rec.get("price"),
        "chg1d": rec.get("chg_1d"),
        "chg1w": rec.get("chg_1w"),
        "chg1m": rec.get("chg_1m"),
        "rsi14": rec.get("rsi14"),
        "sma50": rec.get("sma50"),
        "sma200": rec.get("sma200"),
        "vsSma50": rec.get("vs_sma50"),
        "vsSma200": rec.get("vs_sma200"),
        "relVol": rec.get("rel_vol"),
        "high52w": rec.get("high_52w"),
        "low52w": rec.get("low_52w"),
        "rangePos": rec.get("range_pos"),
        "series": rec.get("series") or [],
        "signals": rec.get("signals") or [],
        "nextEarnings": rec.get("nextEarnings"),
        "score": ai_score(rec),
    }


def ticker_is_indexable(trade_count: int,
                        minimum: int = TICKER_PAGE_MIN_TRADES) -> bool:
    """Only pages carrying real substance are offered to search engines; a
    featured stub exists to make an internal link resolve, nothing more."""
    return trade_count >= minimum


def industry_block(ticker: str, sector_data: dict | None) -> dict | None:
    """The industry a symbol belongs to, for the badge and the filter.

    None when the map does not classify the symbol. The badge then does not
    render and the filter counts the symbol as uncovered, which the page
    states out loud — a missing badge must never read as "belongs nowhere".
    """
    key = sectors.ticker_sector(ticker, sector_data or {})
    if not key:
        return None
    return {"key": key, "label": sectors.label(key, sector_data or {})}


def ticker_payload(ticker: str, trades: list[dict],
                   page_names: list[str] = MEMBER_PAGE_NAMES,
                   indicators: dict | None = None,
                   sector_data: dict | None = None) -> dict:
    """Per-ticker page data: who traded it, how much, and the recent trades with
    a link to each official filing. Dollar figures are bracket **midpoints** —
    an estimate, never a real position size."""
    ts = [t for t in trades if t.get("ticker") == ticker]
    ts.sort(key=lambda t: (t.get("tx_date") or "", t.get("filing_date") or ""),
            reverse=True)

    assets = Counter(t["asset"] for t in ts if t.get("asset"))
    company = clean_company(assets.most_common(1)[0][0] if assets else "", ticker)
    have_page = {n for n in page_names}

    sides = Counter(t.get("type") for t in ts)
    dated = [t for t in ts if t.get("tx_date")]
    late_vals = [days_late(t) for t in ts if days_late(t) is not None]
    late_pos = [d for d in late_vals if d > 0]
    buy_est = sum(_mid(t) for t in ts if t.get("type") == "buy")
    sell_est = sum(_mid(t) for t in ts if t.get("type") == "sell")

    by_member: dict[str, dict] = {}
    for t in ts:
        name = t.get("member")
        if not name:
            continue
        m = by_member.setdefault(name, {
            "name": name, "slug": slugify(name), "party": t.get("party"),
            "chamber": {"senate": "Senate", "executive": "Executive"}.get(
                t.get("chamber"), "House"),
            "trades": 0, "buys": 0, "sells": 0, "est": 0.0,
            "hasPage": name in have_page,
        })
        m["trades"] += 1
        m["est"] += _mid(t)
        if t.get("type") == "buy":
            m["buys"] += 1
        elif t.get("type") == "sell":
            m["sells"] += 1
    top_members = sorted(by_member.values(),
                         key=lambda m: (-m["trades"], -m["est"], m["name"]))

    rows = [{
        "member": t.get("member") or "—",
        "memberSlug": slugify(t.get("member") or ""),
        "hasPage": (t.get("member") or "") in have_page,
        "party": t.get("party"),
        "side": _side_label(t),
        "amountBucket": compact_bucket(t.get("amount_lo"), t.get("amount_hi")),
        "txDate": t.get("tx_date"),
        "filedDate": t.get("filing_date"),
        "daysLate": days_late(t),
        "sourceUrl": t.get("source_url"),
    } for t in ts[:TICKER_TRADE_CAP]]

    return {
        "slug": ticker_slug(ticker),
        "ticker": ticker,
        "company": company,
        # OUR industry grouping (congress/sectors.json), for the page badge and
        # the /tickers filter. None when the map does not classify the symbol,
        # and the surfaces then print their own coverage rather than imply the
        # stock belongs nowhere.
        "industry": industry_block(ticker, sector_data),
        # A featured-watchlist stub exists so the tracker's link resolves;
        # only pages with real substance are offered to search engines.
        "indexable": ticker_is_indexable(len(ts)),
        # Present only for the featured watchlist (the universe we compute
        # indicators for); every other ticker page omits the panel.
        "technical": technical_block(ticker, indicators or {}),
        "summary": {
            "trades": len(ts),
            "members": len(by_member),
            "buys": sides.get("buy", 0),
            "sells": sides.get("sell", 0),
            "other": len(ts) - sides.get("buy", 0) - sides.get("sell", 0),
            "firstTx": min((t["tx_date"] for t in dated), default=None),
            "lastTx": max((t["tx_date"] for t in dated), default=None),
            # The page dateline's "newest filing" — how recent the newest
            # information here is, as opposed to when we last rebuilt the page.
            "lastFiling": max(
                (t["filing_date"] for t in ts if t.get("filing_date")),
                default=None),
            "estBuyLabel": money(buy_est),
            "estSellLabel": money(sell_est),
            "pctLate": round(100 * len(late_pos) / len(late_vals)) if late_vals else 0,
        },
        "topMembers": [{
            "name": m["name"], "slug": m["slug"], "party": m["party"],
            "chamber": m["chamber"], "trades": m["trades"], "buys": m["buys"],
            "sells": m["sells"], "estLabel": money(m["est"]),
            "hasPage": m["hasPage"],
        } for m in top_members[:TICKER_MEMBER_CAP]],
        "trades": rows,
        "tradesShown": len(rows),
    }


def write_ticker_files(trades: list[dict], out_dir: Path,
                       tickers: list[str] | None = None) -> list[str]:
    """Write tickers/<slug>.json for each qualifying ticker + tickers/_index.json.
    Returns the slugs written."""
    comment = (
        "Generated from real official disclosures by congress/landing_data.py "
        "(daily Action). Do not edit by hand. Dollar figures are bracket "
        "midpoints — estimates, not real position sizes."
    )
    names = select_ticker_pages(trades) if tickers is None else tickers
    ind = load_indicators()
    sector_data = sectors.load()
    tickers_dir = out_dir / "tickers"
    tickers_dir.mkdir(parents=True, exist_ok=True)
    index, written = [], []
    unclassified = []
    for tk in names:
        payload = ticker_payload(tk, trades, indicators=ind,
                                 sector_data=sector_data)
        if payload["summary"]["trades"] == 0:
            continue
        if not payload["industry"]:
            unclassified.append(payload["ticker"])
        (tickers_dir / f"{payload['slug']}.json").write_text(
            json.dumps({"_comment": comment, **payload},
                       indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        written.append(payload["slug"])
        index.append({
            "slug": payload["slug"], "ticker": payload["ticker"],
            "company": payload["company"],
            "trades": payload["summary"]["trades"],
            "members": payload["summary"]["members"],
            "buys": payload["summary"]["buys"],
            "sells": payload["summary"]["sells"],
            "lastTx": payload["summary"]["lastTx"],
            "indexable": payload["indexable"],
            "industry": payload["industry"],
        })
    index.sort(key=lambda r: -r["trades"])
    (tickers_dir / "_index.json").write_text(
        json.dumps({"_comment": comment, "tickers": index,
                    "industries": sector_data.get("sectors") or {}},
                   indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    # The page universe is picked fresh every run, so a newly-qualifying stock
    # can arrive with no industry. Say so in the Action log (the holdings
    # NEEDS_REVIEW rule): a silent gap is how a coverage hole survives.
    for tk in unclassified:
        print(f"::warning::no industry for ticker page {tk} — "
              f"add it to congress/sectors.json")
    return written


def write_files(trades: list[dict], out_dir: Path, today: date) -> tuple[int, dict]:
    """Write disclosures.json + stats.json + late.json; returns (rows, stats)
    for logging. Member pages are written separately (write_member_files)."""
    comment = (
        "Generated from real official disclosures by congress/landing_data.py "
        "(daily Action). Do not edit by hand. 'filedDaysLate' counts days past "
        "the STOCK Act's 45-day statutory maximum; 0 = on time."
    )
    rows = feed_payload(trades, set(select_ticker_pages(trades)))
    stats = stats_payload(trades, today)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "disclosures.json").write_text(
        json.dumps({"_comment": comment, "disclosures": rows},
                   indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    (out_dir / "stats.json").write_text(
        json.dumps({"_comment": comment, **stats},
                   indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    (out_dir / "late.json").write_text(
        json.dumps({"_comment": comment, **late_payload(trades, today)},
                   indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    # The market reading lives in ONE file that every ticker page imports.
    # Copying it into each ticker payload would rewrite all 98 of them every
    # morning — the same number, 98 times — and bury the real trade changes in
    # the diff. Always written, even when the reading is absent: the pages
    # import it at build time, so the file has to exist.
    (out_dir / "market.json").write_text(
        json.dumps({"_comment": (
            "Market-wide volatility reading, copied from the indicators run "
            "(congress/market.py). Context only — it never votes in the "
            "mechanical read. Do not edit by hand."),
            "market": load_market()},
                   indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return len(rows), stats
