"""Incremental orchestration: list filings, fetch new ones, merge, prune, write.

The pipeline is chamber-agnostic: each chamber is wired in as a
``ChamberSource`` (see ``congress.cli``), so tests can drive the whole
incremental flow with stub sources and no network.

Output file layout (``docs/data/congress-trades.json``): ``meta`` is
pretty-printed and each trade is one line, so daily auto-commits produce
readable per-trade diffs while staying valid JSON.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Callable

from .normalize import (
    Roster,
    Trade,
    enrich,
    enrich_dict,
    load_featured,
    prune_cutoff,
    trade_sort_key,
)

PACKAGE_DIR = Path(__file__).resolve().parent
REPO_ROOT = PACKAGE_DIR.parent
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "data" / "congress-trades.json"
DEFAULT_STATE = PACKAGE_DIR / "state.json"


class PaperFiling(Exception):
    """Raised by a fetcher when the filing is a scan with no parseable text."""


@dataclass
class ChamberSource:
    """One chamber's listing + fetching, injected by the CLI (or tests)."""

    chamber: str                                  # "senate" | "house"
    list_filings: Callable[[], list]              # → chamber-specific refs
    fetch_trades: Callable[[object], list[Trade]]  # ref → trades; raises
    #   PaperFiling for scans (permanent skip) or any other exception for a
    #   parse error (skipped now, retried on the next run).
    ref_id: Callable[[object], str]
    ref_member: Callable[[object], str]
    ref_filing_date: Callable[[object], str]      # ISO
    ref_url: Callable[[object], str]


@dataclass
class RunResult:
    changed: bool
    fetched: int = 0
    new_trades: int = 0
    paper_skips: int = 0
    parse_errors: int = 0
    recovered_errors: int = 0
    pruned_trades: int = 0
    notes: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Load / save
# ---------------------------------------------------------------------------

def load_output(path: Path) -> dict:
    if not path.exists():
        return {"meta": {}, "trades": [], "skipped_filings": []}
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("meta", {}).get("_sample"):
        # Fixture-derived placeholder committed before the first live run:
        # start fresh so no fake IDs linger in the real dataset.
        return {"meta": {}, "trades": [], "skipped_filings": []}
    return data


def load_state(path: Path) -> dict:
    if not path.exists():
        return {"processed": {"senate": {}, "house": {}}}
    data = json.loads(path.read_text(encoding="utf-8"))
    data.setdefault("processed", {})
    for chamber in ("senate", "house"):
        data["processed"].setdefault(chamber, {})
    return data


def dump_output(output: dict) -> str:
    """Valid JSON with pretty meta and one trade/skip per line (diff-friendly)."""
    compact = dict(separators=(",", ":"), ensure_ascii=False)

    def lines(items):
        return ",\n".join("  " + json.dumps(i, **compact) for i in items)

    parts = ['{\n"meta": ']
    parts.append(json.dumps(output["meta"], indent=1, ensure_ascii=False))
    parts.append(',\n"trades": [\n')
    parts.append(lines(output["trades"]))
    parts.append('\n],\n"skipped_filings": [\n')
    parts.append(lines(output["skipped_filings"]))
    parts.append("\n]\n}\n")
    return "".join(parts)


def save_state(state: dict, path: Path) -> None:
    state["_comment"] = (
        "Processed filing IDs (id -> filing date) so daily runs only fetch "
        "new filings. Generated by congress/pipeline.py; do not edit by hand."
    )
    path.write_text(
        json.dumps(state, indent=1, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------

def run(
    sources: list[ChamberSource],
    *,
    today: date | None = None,
    output_path: Path = DEFAULT_OUTPUT,
    state_path: Path = DEFAULT_STATE,
    limit: int | None = None,
    log: Callable[[str], None] = print,
    dry_run: bool = False,
    generated_at: str | None = None,
) -> RunResult:
    today = today or datetime.now(timezone.utc).date()
    cutoff = prune_cutoff(today)
    output = load_output(output_path)
    state = load_state(state_path)
    roster = Roster.load()
    result = RunResult(changed=False)

    trades = {t["id"]: t for t in output["trades"]}
    skipped = {s["filing_id"]: s for s in output["skipped_filings"]}
    before = _content_key(output)

    for source in sources:
        processed = state["processed"][source.chamber]
        refs = [
            r
            for r in source.list_filings()
            if source.ref_filing_date(r) >= cutoff
            and source.ref_id(r) not in processed
        ]
        if limit is not None and len(refs) > limit:
            log(
                f"{source.chamber}: {len(refs)} new filings, "
                f"limiting to {limit} this run"
            )
            refs = refs[:limit]
        log(f"{source.chamber}: fetching {len(refs)} new filings")
        if dry_run:
            for ref in refs:
                log(
                    f"  would fetch {source.ref_id(ref)} "
                    f"({source.ref_member(ref)}, {source.ref_filing_date(ref)})"
                )
            continue
        for ref in refs:
            fid = source.ref_id(ref)
            result.fetched += 1
            try:
                new = source.fetch_trades(ref)
            except PaperFiling:
                skipped[fid] = _skip_entry(source, ref, "paper")
                processed[fid] = source.ref_filing_date(ref)
                result.paper_skips += 1
                continue
            except Exception as exc:  # parse error: skip now, retry next run
                skipped[fid] = _skip_entry(source, ref, "parse_error")
                result.parse_errors += 1
                log(f"  {source.chamber}:{fid} parse error: {exc}")
                continue
            if fid in skipped:  # a previously failed filing now parses
                del skipped[fid]
                result.recovered_errors += 1
            for trade in new:
                trades[trade.id] = enrich(trade, roster).to_dict()
                result.new_trades += 1
            processed[fid] = source.ref_filing_date(ref)

    # Re-enrich every stored trade so a roster refresh fills party/state on
    # trades ingested before the member existed in members.json.
    for t in trades.values():
        enrich_dict(t, roster)

    # Prune everything (trades, skips, state) outside the two-year window.
    kept = {i: t for i, t in trades.items() if t["filing_date"] >= cutoff}
    result.pruned_trades = len(trades) - len(kept)
    trades = kept
    skipped = {i: s for i, s in skipped.items() if s["filing_date"] >= cutoff}
    for chamber in state["processed"]:
        state["processed"][chamber] = {
            i: d for i, d in state["processed"][chamber].items() if d >= cutoff
        }

    output["trades"] = sorted(trades.values(), key=trade_sort_key)
    output["skipped_filings"] = sorted(
        skipped.values(), key=lambda s: (s["filing_date"], s["filing_id"]), reverse=True
    )
    result.changed = _content_key(output) != before
    if dry_run or not result.changed:
        log("no changes" if not result.changed else "dry run: not writing")
        return result

    output["meta"] = _build_meta(output, state, today, cutoff, generated_at)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(dump_output(output), encoding="utf-8")
    save_state(state, state_path)
    log(
        f"wrote {len(output['trades'])} trades "
        f"({result.new_trades} new, {result.pruned_trades} pruned, "
        f"{len(output['skipped_filings'])} skipped filings) to {output_path}"
    )
    return result


def _skip_entry(source: ChamberSource, ref, reason: str) -> dict:
    return {
        "chamber": source.chamber,
        "member": source.ref_member(ref),
        "filing_date": source.ref_filing_date(ref),
        "reason": reason,
        "filing_id": source.ref_id(ref),
        "source_url": source.ref_url(ref),
    }


def _content_key(output: dict) -> str:
    return json.dumps(
        [output["trades"], output["skipped_filings"]], sort_keys=True
    )


def _build_meta(
    output: dict, state: dict, today: date, cutoff: str, generated_at: str | None
) -> dict:
    prev_version = output.get("meta", {}).get("data_version", "")
    stamp = today.isoformat()
    serial = 1
    if prev_version.startswith(stamp + "."):
        serial = int(prev_version.rsplit(".", 1)[1]) + 1
    return {
        "_comment": (
            "Generated by congress/pipeline.py from official Senate eFD and "
            "House Clerk disclosures. Do not edit by hand. Amounts are the "
            "legal disclosure brackets; filings lag trades by 30-45 days by "
            "law."
        ),
        "generated_at": generated_at
        or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "data_version": f"{stamp}.{serial}",
        "window": {"from": cutoff, "to": today.isoformat()},
        "counts": {
            "trades": len(output["trades"]),
            "members": len({t["member"] for t in output["trades"]}),
            "filings_processed": sum(
                len(v) for v in state["processed"].values()
            ),
            "filings_skipped": len(output["skipped_filings"]),
        },
        "featured": load_featured(),
    }
